# Site
repository: nikhilkoditala/nikhilkoditala.github.io
# favicon: images/favicon.ico

# Personal info
name: Nikhil Koditala
title: Computer Science Student
email: nikhilkodit1@gmail.com
website: nikhilkoditala.github.io

# Social links
twitter_username: Nikhil32901303
github_username:  nikhilkoditala
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: nikhilkoditala
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nikhil and I'm a Final year Computer Science Student. I has experience in working as Research Intern at IIIT Hyderabad.

  I am most skilled in: <mark>NLP</mark> and <mark>Web Development</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: Publications
more_content: | # this will include new lines to allow paragraphs
  <mark>Water Quality Monitoring System using IoT and Machine Learning<mark> accepted for publication and presented in 3rd IEEE International Conference on Research in Intelligent and Computing in Engineering.

# Footer
footer_show_references: true

# Build settings
remote_theme: nikhilkoditala/nikhilkoditala.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
